
version: '3.8'

services:
  frontend:
    build:
      context: ./client
    command: npm run build && npm run export
    volumes:
      - ./client/out:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    environment:
      - DATABASE_URL=postgresql://avatar:avatar123@db:5432/avatar_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: avatar
      POSTGRES_PASSWORD: avatar123
      POSTGRES_DB: avatar_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client/out:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
