
version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    volumes:
      - ./server:/app
    depends_on:
      - wav2lip

  wav2lip:
    build:
      context: ./server/docker/wav2lip
    ports:
      - "5000:5000"
    volumes:
      - wav2lip-uploads:/app/uploads
      - wav2lip-outputs:/app/outputs

volumes:
  wav2lip-uploads:
  wav2lip-outputs:
