
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: avatar
      POSTGRES_PASSWORD: avatar123
      POSTGRES_DB: avatar_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
